name: Smoke test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  scan-testbed:
    name: Scan codeql-nix-testbed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the testbed
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: JamieMagee/codeql-nix-testbed

      - name: Checkout this action
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./codeql-nix-action

      - name: Run codeql-nix-action against the testbed
        uses: ./codeql-nix-action
        with:
          source-root: nix
          category: codeql-nix-smoke-test
